export default [
  {
    name: "Earth forms",
    date: -4_600_000_000,
    link: "https://en.wikipedia.org/wiki/Earth#Formation",
    image: "earth-formation.jpg",
  },
  {
    name: "Cellular life",
    date: -3_800_000_000,
    link: "https://en.wikipedia.org/wiki/Earliest_known_life_forms#Biospheres",
    image: "hydrothermal.jpg",
  },
  {
    name: "Eukaryotes",
    date: -2_200_000_000,
    link: "https://en.wikipedia.org/wiki/Eukaryote#Fossils",
    image: "eukaryote.jpg",
  },
  {
    name: "First plants",
    date: -1_000_000_000,
    link: "https://en.wikipedia.org/wiki/Cyanobacteria",
    image: "first-plants.jpg",
  },
  {
    name: "Cambrian explosion",
    date: -538_000_000,
    link: "https://en.wikipedia.org/wiki/Cambrian",
    image: "cambrian.jpg",
  },
  {
    name: "Amphibians",
    date: -375_000_000,
    link: "https://en.wikipedia.org/wiki/Tiktaalik",
    image: "tiktaalik.jpg",
  },
  {
    name: "Reptiles",
    date: -340_000_000,
    link: "https://en.wikipedia.org/wiki/Casineria",
    image: "casineria.jpg",
  },
  {
    name: "Dinosaurs",
    date: -252_000_000,
    link: "https://en.wikipedia.org/wiki/Dinosaur#Origins_and_early_evolution",
    image: "eoraptor.jpg",
  },
  {
    name: "Extinction event",
    date: -66_000_000,
    link: "https://en.wikipedia.org/wiki/Cretaceous–Paleogene_extinction_event",
    image: "extinction.jpg",
  },
  {
    name: "Australopithecus",
    date: -3_900_000,
    link: "https://en.wikipedia.org/wiki/Australopithecus_afarensis",
    image: "lucy.jpg",
  },
  {
    name: "Stone tools",
    date: -3_300_000,
    link: "https://en.wikipedia.org/wiki/Lomekwi",
    image: "lomekwian.jpg",
  },
  {
    name: "Homo habilis",
    date: -2_300_000,
    link: "https://en.wikipedia.org/wiki/Homo_habilis",
    image: "habilis.jpg",
  },
  {
    name: "Homo erectus",
    date: -1_600_000,
    link: "https://en.wikipedia.org/wiki/Homo_erectus",
    image: "erectus.jpg",
  },
  {
    name: "Neanderthals",
    date: -600_000,
    link: "https://en.wikipedia.org/wiki/Neanderthal",
    image: "neanderthal.jpg",
  },
  {
    name: "Homo sapiens",
    date: -300_000,
    link: "https://en.wikipedia.org/wiki/Human#Evolution",
    image: "human.jpg",
  },
  {
    name: "Cave paintings",
    date: -50_000,
    link: "https://en.wikipedia.org/wiki/Cave_painting",
    image: "sulawesi.jpg",
  },
  { name: "Natufian culture", date: -12_000 },
  { name: "Gobekli Tepe", date: -9500 },
  { name: "Cuneform", date: -3300 },
  { name: "Initial stonehenge", date: -3000 },
  { name: "First pyramid", date: -2600 },
  { name: "Stonehenge", date: -2200 },
  { name: "Last mammoths", date: -2000 },
  { name: "Mycenaean", date: -1700 },
  { name: "Last pyramid", date: -1500 },
  { name: "Bronze age collapse", date: -1200 },
  { name: "Nok Culture", date: -1000 },
  { name: "Kushites", date: -780 },
  { name: "Confucius", date: -500 },
  { name: "Ancient Great Wall", date: -440 },
  { name: "Aristotle", date: -340 },
  {
    name: "Cleopatra",
    date: -40,
    link: "https://en.wikipedia.org/wiki/Cleopatra",
    image: "cleopatra.jpg",
  },
  { name: "Marcus Aurelius", date: 160 },
  { name: "Constantine Byzantium", date: 330 },
  { name: "Fall of Rome", date: 476 },
  { name: "Aryabhata mathematician", date: 500 },
  { name: "Construction of Borobudur", date: 760 },
  { name: "Bagan, Burma", date: 900 },
  { name: "Angkor Wat", date: 1150 },
  { name: "Lalibela, Ethiopia", date: 1200 },
  { name: "Machu Picchu", date: 1400 },
  { name: "Modern Great Wall", date: 1500 },
  { name: "Commercial steam engine", date: 1700 },
  { name: "Eiffel tower", date: 1888 },
  { name: "Man on moon", date: 1969 },
  { name: "Now", date: 2024 },
];
